# Generated by Django 4.2.26 on 2026-04-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_issue_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(help_text='Issue name help text', max_length=100, verbose_name='Name'),
        ),
    ]
